[project]
authors = ["Opher Donchin <donchin@bgu.ac.il>"]
channels = ["conda-forge"]
name = "bme_stats"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
arviz = ">=0.21.0,<0.22"
pymc = ">=5.21.1,<6"
python = ">=3.13.2,<3.14"
ipython = ">=9.0.2,<10"
ipywidgets = ">=8.1.5,<9"
ipympl = ">=0.0.8,<0.0.9"
graphviz = ">=12.2.1,<13"
notebook = ">=7.3.3,<8"
matplotlib = ">=3.10.1,<4"
numpy = ">=2.1.3,<3"
numba = ">=0.61.0,<0.62"
scipy = ">=1.15.2,<2"
pandas = ">=2.2.3,<3"
xarray = ">=2025.3.0,<2026"
pip = ">=25.0.1,<26"
pydot = ">=3.0.4,<4"
nbconvert = ">=7.16.6,<8"
jupytext = ">=1.16.7,<2"

[pypi-dependencies]
bambi = ">=0.15.0, <0.16"
kulprit = ">=0.3.0, <0.4"
nutpie = ">=0.14.3, <0.15"
preliz = ">=0.4.1, <0.5"
threadpoolctl = "*"
