[project]
authors = ["Opher Donchin <donchin@bgu.ac.il>"]
channels = ["conda-forge"]
name = "bme_stats"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
arviz = "==0.20.0"
pymc = "==5.21.1"
python = "==3.11.11"
ipython = "*"
ipywidgets = "7.7.1.*"
ipympl = "*"
graphviz = "*"
notebook = "==6.5.5"
matplotlib = "==3.10.0"
numpy = "==2.0.2"
numba = "==0.60.0"
scipy = "==1.14.1"
pandas = "==2.2.2"
xarray = "==2025.1.2"
pip = "24.1.2.*"
pydot = "==3.0.4"

[pypi-dependencies]
bambi = "*"
kulprit = "*"
nutpie = "*"
preliz = "*"